<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# Simple APIs

## Random User and Fruitvice API Examples

Estimated time needed: **25** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruitvice API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other.

The advantages of using APIs:

*   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more\
    productive.
*   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to
    independently implement some functionality from scratch.

The disadvantage of using APIs:

*   **Secirity**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data\
    breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01#intro) can be found here.

Another example of simple API we will use in this notebook is Fruitvice application. The Fruitvice API webservice which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The webservice is completely free to use and contribute to.

## Example 1: RandomUser API

Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01) page.

## **Get Methods**

*   get_cell()
*   get_city()
*   get_dob()
*   get_email()
*   get_first_name()
*   get_full_name()
*   get_gender()
*   get_id()
*   get_id_number()
*   get_id_type()
*   get_info()
*   get_last_name()
*   get_login_md5()
*   get_login_salt()
*   get_login_sha1()
*   get_login_sha256()
*   get_nat()
*   get_password()
*   get_phone()
*   get_picture()
*   get_postcode()
*   get_registered()
*   get_state()
*   get_street()
*   get_username()
*   get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [2]:
!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... done
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5067 sha256=c5b9612a873874955fade10eb0b2e562dd405116faab71326a63881c9ec0ddc3
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/f8/a9/23/1df3ef7a5177d99b4cba8fa52415e1360bde68f520c2a0e489
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

Then, we will load the necessary libraries.

In [4]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [5]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [8]:
some_list = r.generate_users(10)

In [7]:
some_list

[<randomuser.RandomUser at 0x7efefa4604d0>,
 <randomuser.RandomUser at 0x7efefa460510>,
 <randomuser.RandomUser at 0x7efefa460550>,
 <randomuser.RandomUser at 0x7efefa460590>,
 <randomuser.RandomUser at 0x7efefa4605d0>,
 <randomuser.RandomUser at 0x7efefa460650>,
 <randomuser.RandomUser at 0x7efefa460690>,
 <randomuser.RandomUser at 0x7efefa4606d0>,
 <randomuser.RandomUser at 0x7efefa460710>,
 <randomuser.RandomUser at 0x7efefa460610>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [9]:
name = r.get_full_name()

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [10]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Ümit Yeşilkaya   umit.yesilkaya@example.com
Ryan Edwards   ryan.edwards@example.com
Mikkel Pedersen   mikkel.pedersen@example.com
John Medina   john.medina@example.com
Jabim Rezende   jabim.rezende@example.com
Montserrat Gil   montserrat.gil@example.com
Maciej Selvåg   maciej.selvag@example.com
Astrid Thomsen   astrid.thomsen@example.com
Marek Kück   marek.kuck@example.com
Kaja Hauge   kaja.hauge@example.com

## Exercise 1

In this Exercise, generate photos of the random 5 users.

In [11]:
## Write your code here
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/4.jpg
https://randomuser.me/api/portraits/men/57.jpg
https://randomuser.me/api/portraits/men/4.jpg
https://randomuser.me/api/portraits/men/85.jpg
https://randomuser.me/api/portraits/men/17.jpg
https://randomuser.me/api/portraits/women/85.jpg
https://randomuser.me/api/portraits/men/67.jpg
https://randomuser.me/api/portraits/women/39.jpg
https://randomuser.me/api/portraits/men/59.jpg
https://randomuser.me/api/portraits/women/47.jpg

<details><summary>Click here for the solution</summary>

```python
for user in some_list:
    print (user.get_picture())
```

</details>

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [12]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [13]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Saana Elo,female,Sodankylä,Lapland,saana.elo@example.com,1998-05-07T06:07:13.344Z,https://randomuser.me/api/portraits/women/56.jpg
1,Barb Kim,female,Newcastle upon Tyne,Suffolk,barb.kim@example.com,1982-05-22T12:29:30.239Z,https://randomuser.me/api/portraits/women/64.jpg
2,باران رضاییان,female,نیشابور,بوشهر,brn.rdyyn@example.com,1965-01-26T02:16:40.582Z,https://randomuser.me/api/portraits/women/48.jpg
3,Tobias Jørgensen,male,Roslev,Hovedstaden,tobias.jorgensen@example.com,1959-05-24T02:04:41.543Z,https://randomuser.me/api/portraits/men/68.jpg
4,Charlene Terry,female,Pueblo,South Carolina,charlene.terry@example.com,1954-12-31T23:56:14.045Z,https://randomuser.me/api/portraits/women/36.jpg
5,Sophie Garcia,female,Courbevoie,Bas-Rhin,sophie.garcia@example.com,1971-05-31T09:11:20.589Z,https://randomuser.me/api/portraits/women/42.jpg
6,Lucie Gerard,female,Saint-Denis,Pas-de-Calais,lucie.gerard@example.com,1986-09-28T01:38:41.656Z,https://randomuser.me/api/portraits/women/23.jpg
7,Silke Sørensen,female,Aalborg S.Ø.,Nordjylland,silke.sorensen@example.com,1955-05-11T17:24:42.123Z,https://randomuser.me/api/portraits/women/5.jpg
8,Alex Alves,male,Uberlândia,Rio Grande do Sul,alex.alves@example.com,1968-08-29T03:14:41.466Z,https://randomuser.me/api/portraits/men/0.jpg
9,Efe Süleymanoğlu,male,Karabük,Kırıkkale,efe.suleymanoglu@example.com,1983-11-19T13:17:57.758Z,https://randomuser.me/api/portraits/men/36.jpg

In [14]:
df1 = pd.DataFrame(get_users())

Now we have a *pandas* dataframe that can be used for any testing purposes that the tester might have.

## Example 2: Fruitvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [15]:
import requests
import json

We will obtain the [fruitvice](https://www.fruityvice.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01) API data using `requests.get("url")` function. The data is in a json format.

In [16]:
data = requests.get("https://www.fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [17]:
results = json.loads(data.text)

We will convert our json data into *pandas* data frame.

In [18]:
pd.DataFrame(results)

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Persea,Avocado,84,Lauraceae,Laurales,"{'carbohydrates': 8.53, 'protein': 2, 'fat': 1..."
3,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
4,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."
5,Fragaria,Blueberry,33,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0, 'fat': 0...."
6,Prunus,Cherry,9,Rosaceae,None,"{'carbohydrates': 12, 'protein': 1, 'fat': 0.3..."
7,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,"{'carbohydrates': 9, 'protein': 9, 'fat': 1.5,..."
8,Durio,Durian,60,Malvaceae,Malvales,"{'carbohydrates': 27.1, 'protein': 1.5, 'fat':..."
9,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."
10,Ficus,Fig,68,Moraceae,Rosales,"{'carbohydrates': 19, 'protein': 0.8, 'fat': 0..."
11,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,"{'carbohydrates': 10, 'protein': 0.9, 'fat': 0..."
12,Vitis,Grape,81,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
13,Vitis,Grapes,47,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
14,Malus,GreenApple,72,Rosaceae,Rosales,"{'carbohydrates': 3.1, 'protein': 0.4, 'fat': ..."
15,Psidium,Guava,37,Myrtaceae,Myrtales,"{'carbohydrates': 14, 'protein': 2.6, 'fat': 1..."
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,"{'carbohydrates': 15, 'protein': 1.1, 'fat': 0..."
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,"{'carbohydrates': 14.6, 'protein': 1.14, 'fat'..."
18,Citrus,Lemon,26,Rutaceae,Sapindales,"{'carbohydrates': 9, 'protein': 1.1, 'fat': 0...."
19,Citrus,Lime,44,Rutaceae,Sapindales,"{'carbohydrates': 8.4, 'protein': 0.3, 'fat': ..."
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,"{'carbohydrates': 11.3, 'protein': 0.75, 'fat'..."
21,Litchi,Lychee,67,Sapindaceae,Sapindales,"{'carbohydrates': 17, 'protein': 0.8, 'fat': 0..."
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,"{'carbohydrates': 15, 'protein': 0.82, 'fat': ..."
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,"{'carbohydrates': 8, 'protein': 0, 'fat': 0, '..."
24,Morus,Morus,82,Moraceae,Rosales,"{'carbohydrates': 9.8, 'protein': 1.44, 'fat':..."
25,Citrus,Orange,2,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 1, 'fat': 0...."
26,Carica,Papaya,42,Caricaceae,Caricacea,"{'carbohydrates': 11, 'protein': 0, 'fat': 0.4..."
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,"{'carbohydrates': 22.4, 'protein': 2.2, 'fat':..."
28,Pyrus,Pear,4,Rosaceae,Rosales,"{'carbohydrates': 15, 'protein': 0.4, 'fat': 0..."
29,Diospyros,Persimmon,52,Ebenaceae,Rosales,"{'carbohydrates': 18, 'protein': 0, 'fat': 0, ..."
30,Ananas,Pineapple,10,Bromeliaceae,Poales,"{'carbohydrates': 13.12, 'protein': 0.54, 'fat..."
31,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,"{'carbohydrates': 7, 'protein': 1, 'fat': 0.4,..."
32,Prunus,Plum,71,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.7, 'fat':..."
33,Punica,Pomegranate,79,Lythraceae,Myrtales,"{'carbohydrates': 18.7, 'protein': 1.7, 'fat':..."
34,Rubus,Raspberry,23,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1.2, 'fat': 0..."
35,Fragaria,Strawberry,3,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0.8, 'fat': ..."
36,Citrus,Tangerine,77,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 0, 'fat': 0...."
37,Solanum,Tomato,5,Solanaceae,Solanales,"{'carbohydrates': 3.9, 'protein': 0.9, 'fat': ..."
38,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [19]:
df2 = pd.json_normalize(results)

In [20]:
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Persea,Avocado,84,Lauraceae,Laurales,8.53,2.00,14.66,160,0.66
3,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
4,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
5,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
6,Prunus,Cherry,9,Rosaceae,None,12.00,1.00,0.30,50,8.00
7,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,9.00,9.00,1.50,60,8.00
8,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
9,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,8.00,0.60,0.40,44,3.00
10,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
11,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
12,Vitis,Grape,81,Vitaceae,Vitales,18.10,0.72,0.16,69,16.00
13,Vitis,Grapes,47,Vitaceae,Vitales,18.10,0.72,0.16,69,15.48
14,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
15,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,14.60,1.14,0.50,61,8.90
18,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
19,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
21,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
24,Morus,Morus,82,Moraceae,Rosales,9.80,1.44,0.39,43,8.10
25,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
26,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
28,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
29,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
30,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
31,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,7.00,1.00,0.40,36,3.00
32,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
33,Punica,Pomegranate,79,Lythraceae,Myrtales,18.70,1.70,1.20,83,13.70
34,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
35,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
36,Citrus,Tangerine,77,Rutaceae,Sapindales,8.30,0.00,0.40,45,9.10
37,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
38,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [21]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

## Exercise 2

In this Exercise, find out how many calories are contained in a banana.

In [22]:
# Write your code here
cal_banana = df2.loc[[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

SyntaxError: invalid syntax (4082441774.py, line 3)

<details><summary>Click here for the solution</summary>

```python
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']
```

</details>

## Exercise 3

This [page](https://github.com/public-apis/public-apis#animals) contains a list of free public APIs. Choose any API of your interest and use it to load/extract some information, as shown in the example above.

1.  Using `requests.get("url")` function, load your data.

In [27]:
# Write your code here
data2 = requests.get("https://www.fishwatch.gov/api/species")

<details><summary>Click here for the solution</summary>

```python
data2 = requests.get("https://www.fishwatch.gov/api/species")
```

</details>

2.  Retrieve results using `json.loads()` function.

In [29]:
# Write your code here
results = json.loads(data2.text)

<details><summary>Click here for the solution</summary>

```python
results2 = json.loads(data2.text)
```

</details>

3.  Convert json data into *pandas* data frame.

In [30]:
# Write your code here
df3 = pd.DataFrame(results2)
df3

NameError: name 'results2' is not defined

<details><summary>Click here for the solution</summary>

```python
df3 = pd.DataFrame(results2)
df3
```

</details>

# Congratulations! - You have completed the lab

## Author

[Svitlana Kramar](https://www.linkedin.com/in/svitlana-kramar?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01)

Svitlana is a master’s degree Data Science and Analytics student at University of Calgary, who enjoys travelling, learning new languages and cultures and loves spreading her passion for Data Science.

Copyright © 2020 IBM Corporation. All rights reserved.